# Generated by Django 4.2.4 on 2023-09-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
