# Generated by Django 4.2.4 on 2023-09-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_name',
            field=models.CharField(default='Anonymous', max_length=255),
            preserve_default=False,
        ),
    ]
